### ISSUE TITLE
asset files

### ISSUE THREAD

**Issue by k0a1a** [doublecheck-thequiz/english#1]
Hi,

this is Danja from Tacticaltech/TheGlassroom. I'm about to host your doublecheck sites and i'm noticing that most of the asset files are the same in each language variant/site. Did you consider consolidating it? The simplest would be to make one of the sites contain the assets and link to those from all other variants.

Thanks,

**Comment by FrancyG8** [comment]
Hi Danja!
Nice to meet you, I'm Francesca.
Sorry, I only saw this message now!
We were thinking about doing it, we already wrote to Muhammad about it. We would like to do it as soon as we finish with all the language versions. Is it ok for you?

Have a good day,
Francesca and team

**Comment by k0a1a** [comment]
Hey Francesca,
whenever you are ready. 

Just let Muhammad know about the change and I will update the site. 

Thx
